name: Deploy
on:
  push:
    branches:
      - 'main'
  # pull_request:
  #   branches: main
  #   types: [closed] # Only run when merged
permissions:
  id-token: write
  contents: read
env:
  WORKING_DIRECTORY: "terraform/aws/environments/mng"
jobs:
  deploy:
    # Only run when merged
    # if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    # Use environment variables registered in Environments Secrets on GitHub
    environment: mng
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main # Checkout main branch
      - name: Check Repository
        run: |
          echo "This repository"
          git branch
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.OIDC_ROLE_ARN }}
          aws-region: ap-northeast-1
      - name: Setup
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.0
      - name: Init
        run: terraform init
        working-directory: ${{ env.WORKING_DIRECTORY }}
      - name: Apply
        # run: terraform apply -auto-approve
        run: terraform plan
        working-directory: ${{ env.WORKING_DIRECTORY }}
